Pagination with ajax requests
devmanorg/python.ru pull request #19
Opened 2017-08-02 15:31 UTC by conformist-mw

2017-08-02 18:46 UTC, Melevir requested changes

2017-08-02 18:46 UTC, Melevir commented on main_page/static/main_page/js/index.js
> +	console.log(next_page_url);
Ну кам он :)

2017-08-02 18:46 UTC, Melevir commented on main_page/static/main_page/js/index.js
> +			url: '/' + next_page_url + '&json=true'
Давай лучше сделаем, чтобы форматом по-умолчанию был json.

2017-08-02 18:46 UTC, Melevir commented on main_page/templates/main_page/base.html
> +    {% for i in paginator.page_range %}
`i`? Валли на тебя нет! :)

2017-08-02 18:46 UTC, Melevir commented on main_page/views.py
> +        return response
Не, хочется, чтобы js дёргал не MainPage, а ручку списка карточек. Она бы возвращала json, а он рендерился бы в новые карточки.

2017-08-03 10:35 UTC, conformist-mw commented on main_page/static/main_page/js/index.js
> +	console.log(next_page_url);
да, забыл убрать :)

2017-08-03 10:37 UTC, conformist-mw commented on main_page/static/main_page/js/index.js
> +			url: '/' + next_page_url + '&json=true'
т.е. всегда предполагаем, что нажимается кнопка «ещё», а как-то распознаём, что нажали на пагинацию?

2017-08-03 10:37 UTC, conformist-mw commented on main_page/templates/main_page/base.html
> +    {% for i in paginator.page_range %}
copy/paste driven development. исправлю :)

2017-08-03 10:39 UTC, conformist-mw commented on main_page/views.py
> +        return response
вот тут фишка в том, что если мы будем использовать api cards, то тогда рендер и в шаблонах и в js явно не соответствует dry принципам. Если рендерим все карточки с помощью js, то нужно доработать view или даже подключить rest framework

2017-08-06 04:49 UTC, Melevir commented on main_page/static/main_page/js/index.js
> +			url: '/' + next_page_url + '&json=true'
Не до конца понял вопрос, но похоже, что да.

2017-08-06 04:50 UTC, Melevir commented on main_page/views.py
> +        return response
Да, давай пока сделаем рендер и на беке и на фронте. Потом подумаем, как от этого избавиться без лишнего геммороя.

2017-08-11 13:20 UTC, Melevir commented on cards_api/models.py
> +
Мету лучше в самый низ класса пихать.

2017-08-11 13:20 UTC, merged